export * as demographicsService from "./demographics.service";
export * as userService from "./auth/index";
export * as physiciansService from "./physicians.server";
export * as userInformation from "./users.server";
export * as FormDilogueService from "./FormDilogueService";
export * as patientService from "./patient.server";
export * from "./medicationaallergy.service";
export * as medicalDataService from "./medicaldata.service";
export * as appointmentServices from "./appointments.service";
export * from "./immunizations.service";
export * from "./order.service";
