export const actionTypes = {
  //Authentication
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
  LOGOUT: "USERS_LOGOUT",
  //Users
  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",
  MAIL_VERIFICATION_SUCCESS: "MAIL_VERIFICATION_SUCCESS",
  MAIL_VERIFICATION_FAILURE: "MAIL_VERIFICATION_FAILURE",
  MAIL_VERIFICATION_ERROR: "MAIL_VERIFICATION_ERROR",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "USERS_GETALL_SUCCESS",
  UPDATE_USER_FAILURE: "USERS_GETALL_FAILURE",

  //Utilities
  OPEN_FORM_DIALOG: "OPEN_FORM_DIALOG",
  CLOSE_FROM_DIALOG: "CLOSE_FROM_DIALOG",
  Dilouge_FAILURE: "Dilouge_FAILURE",
  Dilouge_SUCCESS: "Dilouge_SUCCESS",

  //Appointments
  GET_ALL_APPOINTMENTS_REQUEST: "GET_ALL_APPOINTMENTS_REQUEST",
  GET_ALL_APPOINTMENTS_SUCCESS: "GET_ALL_APPOINTMENTS_SUCCESS",
  GET_ALL_APPOINTMENTS_FAILURE: "GET_ALL_APPOINTMENTS_FAILURE",

  ADD_APPOINTMENTS_REQUEST: "ADD_APPOINTMENTS_REQUEST",
  ADD_APPOINTMENTS_SUCCESS: "ADD_APPOINTMENTS_SUCCESS",
  ADD_APPOINTMENTS_FAILURE: "ADD_APPOINTMENTS_FAILURE",

  UPDATE_APPOINTMENT_REQUEST: " UPDATE_APPOINTMENT_REQUEST",
  UPDATE_APPOINTMENT_SUCCESS: " UPDATE_APPOINTMENT_SUCCESS",
  UPDATE_APPOINTMENT_FAILURE: " UPDATE_APPOINTMENT_FAILURE",

  DELETE_APPOINTMENT_REQUEST: " DELETE_APPOINTMENT_REQUEST",
  DELETE_APPOINTMENT_SUCCESS: " DELETE_APPOINTMENT_SUCCESS",
  DELETE_APPOINTMENT_FAILURE: "DELETE_APPOINTMENT_FAILURE",

  //Medical Data
  GET_ALL_AELLERGIES_REQUEST: "GET_ALL_AELLERGIES_REQUEST",
  GET_ALL_AELLERGIES_SUCCESS: "GET_ALL_AELLERGIES_SUCCESS",
  GET_ALL_AELLERGIES_FAILURE: "GET_ALL_AELLERGIES_FAILURE",
  GET_ALL_MEDICATIONS_REQUEST: "GET_ALL_MEDICATIONS_REQUEST",
  GET_ALL_MEDICATIONS_SUCCESS: "GET_ALL_MEDICATIONS_SUCCESS",
  GET_ALL_MEDICATIONS_FAILURE: "GET_ALL_MEDICATIONS_FAILURE",

  //DemoGraphics
  GETALL_DEMOGRAPHICS_REQUEST: "DEMOGRAPHICS_GETALL_DEMOGRAPHICS_REQUEST",
  GETALL_DEMOGRAPHICS_SUCCESS: "DEMOGRAPHICS_GETALL_DEMOGRAPHICS_SUCCESS",
  GETALL_DEMOGRAPHICS_FAILURE: "DEMOGRAPHICS_GETALL_DEMOGRAPHICS_FAILURE",
  POST_DEMOGRAPHICS_REQUEST: "DEMOGRAPHICS_POST_DEMOGRAPHICS_REQUEST",
  POST_DEMOGRAPHICS_SUCCESS: "DEMOGRAPHICS_POST_DEMOGRAPHICS_SUCCESS",
  POST_DEMOGRAPHICS_FAILURE: "DEMOGRAPHICS_POST_DEMOGRAPHICS_FAILURE",
  DELETE_DEMOGRAPHICS: "DEMOGRAPHICS_DELETE_DEMOGRAPHICS",
  UPDATE_DEMOGRAPHICS_REQUEST: "UPDATE_DEMOGRAPHICS_REQUEST",
  UPDATE_DEMOGRAPHICS_SUCCESS: "UPDATE_DEMOGRAPHICS_SUCCESS",
  UPDATE_DEMOGRAPHICS_FAILED: "UPDATE_DEMOGRAPHICS_FAILED",

  //Medications and Allergies
  MEDICATION_GETALL_REQUEST: "MEDICATION_GETALL_REQUEST",
  MEDICATION_GETALL_SUCCESS: "MEDICATION_GETALL_SUCCESS",
  MEDICATION_GETALL_FAILURE: "MEDICATION_GETALL_FAILURE",
  MEDICATION_UPDATEALL_REQUEST: "MEDICATION_UPDATEALL_REQUEST",
  MEDICATION_UPDATEALL_SUCCESS: "MEDICATION_UPDATEALL_SUCCESS",
  MEDICATION_UPDATEALL_FAILURE: "MEDICATION_UPDATEALL_FAILURE",
};
